export const AUTH_ACTIONS = {
  SET_LOADING: 'SET_LOADING',
  SET_STEP: 'SET_STEP',
  SET_EMAIL: 'SET_EMAIL',
  SET_PHONE: 'SET_PHONE',
  SET_EMAIL_VERIFIED: 'SET_EMAIL_VERIFIED',
  SET_PHONE_VERIFIED: 'SET_PHONE_VERIFIED',
  SET_BIOMETRIC_VERIFIED: 'SET_BIOMETRIC_VERIFIED',
  SET_PROFILE_CREATED: 'SET_PROFILE_CREATED',
  SET_AUTHENTICATED: 'SET_AUTHENTICATED',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_USER_ID: 'SET_USER_ID',
  SET_ERROR: 'SET_ERROR',
  SET_REFERRER_VALID: 'SET_REFERRER_VALID',
  SET_FALLBACK_QUESTIONS: 'SET_FALLBACK_QUESTIONS',
  SET_FALLBACK_SETUP_COMPLETE: 'SET_FALLBACK_SETUP_COMPLETE',
  SET_BIOMETRIC_KEYS: 'SET_BIOMETRIC_KEYS',
  SET_SECURITY_QUESTIONS_SETUP: 'SET_SECURITY_QUESTIONS_SETUP',
  SET_COLLECTED_QUESTIONS: 'SET_COLLECTED_QUESTIONS',
  SET_FALLBACK_STEP: 'SET_FALLBACK_STEP',
  RESET_AUTH: 'RESET_AUTH',
  SET_OTP_SENT: 'SET_OTP_SENT',
  SET_RESEND_COOLDOWN: 'SET_RESEND_COOLDOWN'
};

export const initialAuthState = {
  isAuthenticated: false,
  isLoading: false,
  currentStep: 1,
  email: '',
  phone: '',
  userId: null,
  emailVerified: false,
  phoneVerified: false,
  biometricVerified: false,
  profileCreated: false,
  userData: null,
  error: null,
  isValidReferrer: false,
  referrerInfo: null,
  otpSent: false,
  resendCooldown: 0,
  fallbackQuestions: [],
  fallbackSetupComplete: false,
  biometricKeys: null,
  securityQuestionsSetup: false,
  collectedSecurityQuestions: [],
  fallbackStep: null
};